name = "epic-gaming"
author = "quaoz"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "360eb16b382be55c130c396516f384cf1e0c5d79f7d87537524cba3636b26a2d"

[versions]
fabric = "0.16.14"
minecraft = "1.21.6"

[options]
acceptable-game-versions = ["1.21"]
