name = "epic-gaming"
author = "quaoz"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aee62269e0c2fdb05387e1ade3d0443a909249a85d16e12d5de3cbd0b9cb4af5"

[versions]
fabric = "0.16.14"
minecraft = "1.21.6"

[options]
acceptable-game-versions = ["1.21"]
