name = "epic-gaming"
author = "quaoz"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "001391dd2f4b36adfba05961428559b8eafe02af66fa2a55a42c3ce3bb5b08bd"

[versions]
fabric = "0.16.14"
minecraft = "1.21.6"

[options]
acceptable-game-versions = ["1.21"]
